# Operations Pandas

## sum mean std min max

In [3]:
import pandas as pd 
import numpy as np

In [5]:
df_students = pd.read_csv('students_exam_scores.csv')

In [7]:
df_students.head()

       Ad   Soyad Cinsiyet  Matematik  Ingilizce  Turkce
0   Ahmet  Yılmaz    Erkek         78         85      82
1  Mehmet    Kaya    Erkek         65         70      68
2    Ayşe   Demir    Kadın         90         88      91
3   Fatma   Şahin    Kadın         72         75      80
4     Ali   Çelik    Erkek         85         79      77

In [9]:
df_students["ortalama"] = (df_students["Matematik"] + df_students["Turkce"]+df_students["Ingilizce"]) /3

In [11]:
df_students.round(2)

         Ad     Soyad Cinsiyet  Matematik  Ingilizce  Turkce  ortalama
0     Ahmet    Yılmaz    Erkek         78         85      82     81.67
1    Mehmet      Kaya    Erkek         65         70      68     67.67
2      Ayşe     Demir    Kadın         90         88      91     89.67
3     Fatma     Şahin    Kadın         72         75      80     75.67
4       Ali     Çelik    Erkek         85         79      77     80.33
5    Zeynep     Aydın    Kadın         92         90      89     90.33
6     Hasan    Arslan    Erkek         55         60      58     57.67
7     Emine     Doğan    Kadın         83         87      85     85.00
8   Mustafa     Kılıç    Erkek         74         69      72     71.67
9      Elif      Kurt    Kadın         88         91      90     89.67
10    Murat   Özdemir    Erkek         66         64      70     66.67
11   Hatice       Koç    Kadın         79         82      81     80.67
12  İbrahim    Yıldız    Erkek         71         73      69     71.00
13     Seda      Acar    Kadın         95         93      94     94.00
14    Burak     Polat    Erkek         62         67      65     64.67
15      Gül   Bozkurt    Kadın         84         88      86     86.00
16   Serkan       Taş    Erkek         76         72      74     74.00
17    Ceren     Erdem    Kadın         89         92      90     90.33
18     Okan     Güneş    Erkek         58         61      63     60.67
19    Derya     Bulut    Kadın         81         84      83     82.67
20    Kemal     Aksoy    Erkek         69         71      70     70.00
21    Nazlı     Turan    Kadın         93         95      94     94.00
22   Volkan    Öztürk    Erkek         64         66      67     65.67
23    Merve    Karaca    Kadın         87         89      88     88.00
24     Onur      Köse    Erkek         73         75      74     74.00
25    Selin     Ergin    Kadın         91         90      92     91.00
26     Emre      Kara    Erkek         68         70      69     69.00
27     Buse     Sezer    Kadın         85         87      86     86.00
28    Yusuf    Kaplan    Erkek         77         76      78     77.00
29    Melis      Avcı    Kadın         94         93      95     94.00
30      Can      Ateş    Erkek         72         74      73     73.00
31    Pelin     Duman    Kadın         88         86      89     87.67
32     Eren     Çınar    Erkek         63         65      64     64.00
33    Tuğçe       Şen    Kadın         90         91      92     91.00
34    Barış    Yalçın    Erkek         75         77      76     76.00
35     Aslı     Güler    Kadın         89         90      88     89.00
36    Tolga      Özer    Erkek         67         69      68     68.00
37     Nisa      Sarı    Kadın         92         94      93     93.00
38     Kaan     Altun    Erkek         74         72      73     73.00
39    Leyla    Toprak    Kadın         86         88      87     87.00
40    Hakan    Durmaz    Erkek         60         62      61     61.00
41    Sibel    Keskin    Kadın         93         92      94     93.00
42   Serhat    Ekinci    Erkek         71         70      72     71.00
43  Yasemin     Uysal    Kadın         88         89      90     89.00
44   Furkan     Çoban    Erkek         66         68      67     67.00
45     Esra     Aktaş    Kadın         91         93      92     92.00
46    Tamer    Bayrak    Erkek         79         78      80     79.00
47    Gamze  Demirtaş    Kadın         87         86      88     87.00
48   Levent   Karaman    Erkek         70         72      71     71.00
49     İrem      Önal    Kadın         95         94      96     95.00

In [15]:
df_students["Cinsiyet"].value_counts()

Cinsiyet
Erkek    25
Kadın    25
Name: count, dtype: int64

In [16]:
df_students["Cinsiyet"].value_counts(normalize = True)

Cinsiyet
Erkek    0.5
Kadın    0.5
Name: proportion, dtype: float64

In [18]:
df_students.sort_values(['ortalama'],ascending= False)

         Ad     Soyad Cinsiyet  Matematik  Ingilizce  Turkce   ortalama
49     İrem      Önal    Kadın         95         94      96  95.000000
13     Seda      Acar    Kadın         95         93      94  94.000000
29    Melis      Avcı    Kadın         94         93      95  94.000000
21    Nazlı     Turan    Kadın         93         95      94  94.000000
41    Sibel    Keskin    Kadın         93         92      94  93.000000
37     Nisa      Sarı    Kadın         92         94      93  93.000000
45     Esra     Aktaş    Kadın         91         93      92  92.000000
33    Tuğçe       Şen    Kadın         90         91      92  91.000000
25    Selin     Ergin    Kadın         91         90      92  91.000000
17    Ceren     Erdem    Kadın         89         92      90  90.333333
5    Zeynep     Aydın    Kadın         92         90      89  90.333333
9      Elif      Kurt    Kadın         88         91      90  89.666667
2      Ayşe     Demir    Kadın         90         88      91  89.666667
43  Yasemin     Uysal    Kadın         88         89      90  89.000000
35     Aslı     Güler    Kadın         89         90      88  89.000000
23    Merve    Karaca    Kadın         87         89      88  88.000000
31    Pelin     Duman    Kadın         88         86      89  87.666667
47    Gamze  Demirtaş    Kadın         87         86      88  87.000000
39    Leyla    Toprak    Kadın         86         88      87  87.000000
15      Gül   Bozkurt    Kadın         84         88      86  86.000000
27     Buse     Sezer    Kadın         85         87      86  86.000000
7     Emine     Doğan    Kadın         83         87      85  85.000000
19    Derya     Bulut    Kadın         81         84      83  82.666667
0     Ahmet    Yılmaz    Erkek         78         85      82  81.666667
11   Hatice       Koç    Kadın         79         82      81  80.666667
4       Ali     Çelik    Erkek         85         79      77  80.333333
46    Tamer    Bayrak    Erkek         79         78      80  79.000000
28    Yusuf    Kaplan    Erkek         77         76      78  77.000000
34    Barış    Yalçın    Erkek         75         77      76  76.000000
3     Fatma     Şahin    Kadın         72         75      80  75.666667
16   Serkan       Taş    Erkek         76         72      74  74.000000
24     Onur      Köse    Erkek         73         75      74  74.000000
30      Can      Ateş    Erkek         72         74      73  73.000000
38     Kaan     Altun    Erkek         74         72      73  73.000000
8   Mustafa     Kılıç    Erkek         74         69      72  71.666667
48   Levent   Karaman    Erkek         70         72      71  71.000000
42   Serhat    Ekinci    Erkek         71         70      72  71.000000
12  İbrahim    Yıldız    Erkek         71         73      69  71.000000
20    Kemal     Aksoy    Erkek         69         71      70  70.000000
26     Emre      Kara    Erkek         68         70      69  69.000000
36    Tolga      Özer    Erkek         67         69      68  68.000000
1    Mehmet      Kaya    Erkek         65         70      68  67.666667
44   Furkan     Çoban    Erkek         66         68      67  67.000000
10    Murat   Özdemir    Erkek         66         64      70  66.666667
22   Volkan    Öztürk    Erkek         64         66      67  65.666667
14    Burak     Polat    Erkek         62         67      65  64.666667
32     Eren     Çınar    Erkek         63         65      64  64.000000
40    Hakan    Durmaz    Erkek         60         62      61  61.000000
18     Okan     Güneş    Erkek         58         61      63  60.666667
6     Hasan    Arslan    Erkek         55         60      58  57.666667

In [22]:
df_students.sort_values("Ad",ascending= False,
                       key = lambda col:col.str.lower())

         Ad     Soyad Cinsiyet  Matematik  Ingilizce  Turkce   ortalama
5    Zeynep     Aydın    Kadın         92         90      89  90.333333
28    Yusuf    Kaplan    Erkek         77         76      78  77.000000
43  Yasemin     Uysal    Kadın         88         89      90  89.000000
22   Volkan    Öztürk    Erkek         64         66      67  65.666667
33    Tuğçe       Şen    Kadın         90         91      92  91.000000
36    Tolga      Özer    Erkek         67         69      68  68.000000
46    Tamer    Bayrak    Erkek         79         78      80  79.000000
41    Sibel    Keskin    Kadın         93         92      94  93.000000
16   Serkan       Taş    Erkek         76         72      74  74.000000
42   Serhat    Ekinci    Erkek         71         70      72  71.000000
25    Selin     Ergin    Kadın         91         90      92  91.000000
13     Seda      Acar    Kadın         95         93      94  94.000000
31    Pelin     Duman    Kadın         88         86      89  87.666667
24     Onur      Köse    Erkek         73         75      74  74.000000
18     Okan     Güneş    Erkek         58         61      63  60.666667
37     Nisa      Sarı    Kadın         92         94      93  93.000000
21    Nazlı     Turan    Kadın         93         95      94  94.000000
8   Mustafa     Kılıç    Erkek         74         69      72  71.666667
10    Murat   Özdemir    Erkek         66         64      70  66.666667
23    Merve    Karaca    Kadın         87         89      88  88.000000
29    Melis      Avcı    Kadın         94         93      95  94.000000
1    Mehmet      Kaya    Erkek         65         70      68  67.666667
39    Leyla    Toprak    Kadın         86         88      87  87.000000
48   Levent   Karaman    Erkek         70         72      71  71.000000
20    Kemal     Aksoy    Erkek         69         71      70  70.000000
38     Kaan     Altun    Erkek         74         72      73  73.000000
49     İrem      Önal    Kadın         95         94      96  95.000000
12  İbrahim    Yıldız    Erkek         71         73      69  71.000000
11   Hatice       Koç    Kadın         79         82      81  80.666667
6     Hasan    Arslan    Erkek         55         60      58  57.666667
40    Hakan    Durmaz    Erkek         60         62      61  61.000000
15      Gül   Bozkurt    Kadın         84         88      86  86.000000
47    Gamze  Demirtaş    Kadın         87         86      88  87.000000
44   Furkan     Çoban    Erkek         66         68      67  67.000000
3     Fatma     Şahin    Kadın         72         75      80  75.666667
45     Esra     Aktaş    Kadın         91         93      92  92.000000
32     Eren     Çınar    Erkek         63         65      64  64.000000
26     Emre      Kara    Erkek         68         70      69  69.000000
7     Emine     Doğan    Kadın         83         87      85  85.000000
9      Elif      Kurt    Kadın         88         91      90  89.666667
19    Derya     Bulut    Kadın         81         84      83  82.666667
17    Ceren     Erdem    Kadın         89         92      90  90.333333
30      Can      Ateş    Erkek         72         74      73  73.000000
27     Buse     Sezer    Kadın         85         87      86  86.000000
14    Burak     Polat    Erkek         62         67      65  64.666667
34    Barış    Yalçın    Erkek         75         77      76  76.000000
2      Ayşe     Demir    Kadın         90         88      91  89.666667
35     Aslı     Güler    Kadın         89         90      88  89.000000
4       Ali     Çelik    Erkek         85         79      77  80.333333
0     Ahmet    Yılmaz    Erkek         78         85      82  81.666667