In [2]:
import pandas as pd
df_students = pd.read_csv('students_exam_scores.csv')

In [14]:
# print cinsiyeti erkek olanlar
df_students[df_students["Cinsiyet"]== "Erkek" ]

         Ad    Soyad Cinsiyet  Matematik  Ingilizce  Turkce
0     Ahmet   Yılmaz    Erkek         78         85      82
1    Mehmet     Kaya    Erkek         65         70      68
4       Ali    Çelik    Erkek         85         79      77
6     Hasan   Arslan    Erkek         55         60      58
8   Mustafa    Kılıç    Erkek         74         69      72
10    Murat  Özdemir    Erkek         66         64      70
12  İbrahim   Yıldız    Erkek         71         73      69
14    Burak    Polat    Erkek         62         67      65
16   Serkan      Taş    Erkek         76         72      74
18     Okan    Güneş    Erkek         58         61      63
20    Kemal    Aksoy    Erkek         69         71      70
22   Volkan   Öztürk    Erkek         64         66      67
24     Onur     Köse    Erkek         73         75      74
26     Emre     Kara    Erkek         68         70      69
28    Yusuf   Kaplan    Erkek         77         76      78
30      Can     Ateş    Erkek         72         74      73
32     Eren    Çınar    Erkek         63         65      64
34    Barış   Yalçın    Erkek         75         77      76
36    Tolga     Özer    Erkek         67         69      68
38     Kaan    Altun    Erkek         74         72      73
40    Hakan   Durmaz    Erkek         60         62      61
42   Serhat   Ekinci    Erkek         71         70      72
44   Furkan    Çoban    Erkek         66         68      67
46    Tamer   Bayrak    Erkek         79         78      80
48   Levent  Karaman    Erkek         70         72      71

In [13]:
# print cinsiyeti erkek olanlar ve matematikten 70 ustu alanlar
df_students[(df_students["Cinsiyet"]== "Erkek") & (df_students["Matematik"] >= 70) ]

         Ad    Soyad Cinsiyet  Matematik  Ingilizce  Turkce
0     Ahmet   Yılmaz    Erkek         78         85      82
4       Ali    Çelik    Erkek         85         79      77
8   Mustafa    Kılıç    Erkek         74         69      72
12  İbrahim   Yıldız    Erkek         71         73      69
16   Serkan      Taş    Erkek         76         72      74
24     Onur     Köse    Erkek         73         75      74
28    Yusuf   Kaplan    Erkek         77         76      78
30      Can     Ateş    Erkek         72         74      73
34    Barış   Yalçın    Erkek         75         77      76
38     Kaan    Altun    Erkek         74         72      73
42   Serhat   Ekinci    Erkek         71         70      72
46    Tamer   Bayrak    Erkek         79         78      80
48   Levent  Karaman    Erkek         70         72      71

In [16]:
# ingilizce notu 80 ve altinda olanlar
df_students[df_students["Ingilizce"]<=80]

         Ad    Soyad Cinsiyet  Matematik  Ingilizce  Turkce
1    Mehmet     Kaya    Erkek         65         70      68
3     Fatma    Şahin    Kadın         72         75      80
4       Ali    Çelik    Erkek         85         79      77
6     Hasan   Arslan    Erkek         55         60      58
8   Mustafa    Kılıç    Erkek         74         69      72
10    Murat  Özdemir    Erkek         66         64      70
12  İbrahim   Yıldız    Erkek         71         73      69
14    Burak    Polat    Erkek         62         67      65
16   Serkan      Taş    Erkek         76         72      74
18     Okan    Güneş    Erkek         58         61      63
20    Kemal    Aksoy    Erkek         69         71      70
22   Volkan   Öztürk    Erkek         64         66      67
24     Onur     Köse    Erkek         73         75      74
26     Emre     Kara    Erkek         68         70      69
28    Yusuf   Kaplan    Erkek         77         76      78
30      Can     Ateş    Erkek         72         74      73
32     Eren    Çınar    Erkek         63         65      64
34    Barış   Yalçın    Erkek         75         77      76
36    Tolga     Özer    Erkek         67         69      68
38     Kaan    Altun    Erkek         74         72      73
40    Hakan   Durmaz    Erkek         60         62      61
42   Serhat   Ekinci    Erkek         71         70      72
44   Furkan    Çoban    Erkek         66         68      67
46    Tamer   Bayrak    Erkek         79         78      80
48   Levent  Karaman    Erkek         70         72      71