In [2]:
import pandas as pd
import numpy as np

In [6]:
vs = pd.DataFrame({"anahtar": list("ABC")*2,
                  "veri1":range(6),
                  "veri2":np.arange(5,11)})

In [7]:
vs

  anahtar  veri1  veri2
0       A      0      5
1       B      1      6
2       C      2      7
3       A      3      8
4       B      4      9
5       C      5     10

In [8]:
grup = vs.groupby("anahtar")

In [11]:
grup.aggregate(["min","median","max"])

        veri1            veri2
          min median max   min median max
anahtar
A           0    1.5   3     5    6.5   8
B           1    2.5   4     6    7.5   9
C           2    3.5   5     7    8.5  10

In [13]:
grup.agg({"veri1":"min","veri2":"max"})

         veri1  veri2
anahtar
A            0      8
B            1      9
C            2     10

In [16]:
def f(x):
    return x.min() - x.max()
grup.agg(f)

         veri1  veri2
anahtar
A           -3     -3
B           -3     -3
C           -3     -3

In [18]:
veri = pd.DataFrame({"harf":list("ABC")*4,
                    "sayi":["bir","iki"]*6,
                    "v1":np.random.randn(12),
                    "v2":np.arange(10,33,2)})

In [19]:
veri

   harf sayi        v1  v2
0     A  bir -1.123349  10
1     B  iki -0.339289  12
2     C  bir -0.425582  14
3     A  iki  0.143342  16
4     B  bir  1.737582  18
5     C  iki  1.356356  20
6     A  bir -1.405299  22
7     B  iki  0.409775  24
8     C  bir -0.126124  26
9     A  iki  0.060289  28
10    B  bir  1.071707  30
11    C  iki  0.414292  32

In [21]:
grup = veri.groupby(["harf","sayi"])

In [22]:
grup_v1 = grup["v1"]

In [23]:
grup_v1.agg("mean")

harf  sayi
A     bir    -1.264324
      iki     0.101815
B     bir     1.404644
      iki     0.035243
C     bir    -0.275853
      iki     0.885324
Name: v1, dtype: float64

In [24]:
grup_v1.agg(["mean","std",f])

               mean       std         f
harf sayi
A    bir  -1.264324  0.199369 -0.281950
     iki   0.101815  0.058728 -0.083054
B    bir   1.404644  0.470845 -0.665875
     iki   0.035243  0.529668 -0.749064
C    bir  -0.275853  0.211749 -0.299458
     iki   0.885324  0.666140 -0.942064

In [25]:
grup_v1.agg([("ortalama","mean"),("standart sapma","std")])

           ortalama  standart sapma
harf sayi
A    bir  -1.264324        0.199369
     iki   0.101815        0.058728
B    bir   1.404644        0.470845
     iki   0.035243        0.529668
C    bir  -0.275853        0.211749
     iki   0.885324        0.666140

In [31]:
yeni_veri_seti = pd.DataFrame(np.arange(8).reshape(4,2),
                             index = ["bir","iki","uc","dort"],
                             columns= ["sayi1","sayi2"])

In [33]:
yeni_veri_seti.sayi1

bir     0
iki     2
uc      4
dort    6
Name: sayi1, dtype: int64

In [34]:
veri2 = pd.DataFrame({"ogrenci":[32,45,28,42,38],
                     "grup_adi":["dans","yuzme","dans","yuzme","futbol"]}) 
veri2

   ogrenci grup_adi
0       32     dans
1       45    yuzme
2       28     dans
3       42    yuzme
4       38   futbol