In [3]:
import numpy as np
import pandas as pd

In [14]:
data = pd.DataFrame([[1,2,3],[2,1,3]],
    index = ["A","B"]
)

In [15]:
data

   0  1  2
A  1  2  3
B  2  1  3

In [11]:
data.loc["A"]
data.loc["C"]
data

0    3
Name: C, dtype: int64

In [18]:
veri = pd.Series(np.random.randn(8),
                index= [["a","a","a","b","b","b","c","c"],
                       [1,2,3,1,2,3,1,2]])
veri

a  1    0.234678
   2    0.234752
   3    0.724804
b  1   -0.986634
   2   -0.815475
   3   -0.707355
c  1    0.255083
   2   -1.354254
dtype: float64

In [22]:
veri.index

MultiIndex([('a', 1),
            ('a', 2),
            ('a', 3),
            ('b', 1),
            ('b', 2),
            ('b', 3),
            ('c', 1),
            ('c', 2)],
           )

In [31]:
veri["a":"b"]

a  1    0.234678
   2    0.234752
   3    0.724804
b  1   -0.986634
   2   -0.815475
   3   -0.707355
dtype: float64

In [32]:
veri.loc[["a","c"]]

a  1    0.234678
   2    0.234752
   3    0.724804
c  1    0.255083
   2   -1.354254
dtype: float64

In [36]:
veri.loc[:,1]

a    0.234678
b   -0.986634
c    0.255083
dtype: float64

In [37]:
veri.unstack()

          1         2         3
a  0.234678  0.234752  0.724804
b -0.986634 -0.815475 -0.707355
c  0.255083 -1.354254       NaN

In [39]:
veri.unstack().stack()

a  1    0.234678
   2    0.234752
   3    0.724804
b  1   -0.986634
   2   -0.815475
   3   -0.707355
c  1    0.255083
   2   -1.354254
dtype: float64

In [45]:
vs = pd.DataFrame(np.arange(12).reshape(4,3),
                 index=[["a","a","b","b"],[1,2,1,2]],
                        columns=[["say","say","soz"],
                                ["mat","fiz","edb"]])
vs

    say     soz
    mat fiz edb
a 1   0   1   2
  2   3   4   5
b 1   6   7   8
  2   9  10  11

In [47]:
vs.index.names= ["sinif","sinav"]
vs.columns.names=["alan","ders"]

In [48]:
vs

alan        say     soz
ders        mat fiz edb
sinif sinav
a     1       0   1   2
      2       3   4   5
b     1       6   7   8
      2       9  10  11

In [49]:
vs["say"]

ders         mat  fiz
sinif sinav
a     1        0    1
      2        3    4
b     1        6    7
      2        9   10

In [51]:
vs.swaplevel("sinif","sinav")

alan        say     soz
ders        mat fiz edb
sinav sinif
1     a       0   1   2
2     a       3   4   5
1     b       6   7   8
2     b       9  10  11

In [52]:
vs.sort_index(level=1)

alan        say     soz
ders        mat fiz edb
sinif sinav
a     1       0   1   2
b     1       6   7   8
a     2       3   4   5
b     2       9  10  11

In [55]:
vs.groupby(level="sinav").sum()

alan  say     soz
ders  mat fiz edb
sinav
1       6   8  10
2      12  14  16

In [56]:
vs.groupby(level= "alan",axis=1).sum()

/var/folders/nn/fmmg6g2d0lg8mt_0mvywycv80000gn/T/ipykernel_23518/2221920076.py:1: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  vs.groupby(level= "alan",axis=1).sum()

alan         say  soz
sinif sinav
a     1        1    2
      2        7    5
b     1       13    8
      2       19   11

In [57]:
veri = pd.DataFrame({"x":range(8),
                    "y":range(8,0,-1),
                    "a":["bir","bir","bir","bir","iki","iki","iki","iki"],
                    "b":[0,1,2,3,0,1,2,3]})

In [59]:
veri

   x  y    a  b
0  0  8  bir  0
1  1  7  bir  1
2  2  6  bir  2
3  3  5  bir  3
4  4  4  iki  0
5  5  3  iki  1
6  6  2  iki  2
7  7  1  iki  3

In [62]:
veri2 = veri.set_index(["a","b"])
#verideki a,b yi index olarak atiyor

In [61]:
veri2

       x  y
a   b
bir 0  0  8
    1  1  7
    2  2  6
    3  3  5
iki 0  4  4
    1  5  3
    2  6  2
    3  7  1

In [64]:
veri3 = veri.set_index(["a","b"],drop = False)
veri3
#bu sayede drop false ile veriden dusmedi

       x  y    a  b
a   b
bir 0  0  8  bir  0
    1  1  7  bir  1
    2  2  6  bir  2
    3  3  5  bir  3
iki 0  4  4  iki  0
    1  5  3  iki  1
    2  6  2  iki  2
    3  7  1  iki  3

In [65]:
veri2.reset_index()

     a  b  x  y
0  bir  0  0  8
1  bir  1  1  7
2  bir  2  2  6
3  bir  3  3  5
4  iki  0  4  4
5  iki  1  5  3
6  iki  2  6  2
7  iki  3  7  1

In [71]:
veri3.loc["bir",0]

x      0
y      8
a    bir
b      0
Name: (bir, 0), dtype: object