In [1]:
import pandas as pd

url = "https://storage.googleapis.com/kagglesdsdata/datasets/10376752/16184030/iphone_sales_dataset.csv?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gcp-kaggle-com%40kaggle-161607.iam.gserviceaccount.com%2F20260520%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20260520T171448Z&X-Goog-Expires=259200&X-Goog-SignedHeaders=host&X-Goog-Signature=92cd15daa766744583d95c8db1c34ad0ae2328096fc4a8d029419343644335a5ecefb1e908be0313bb0ce42e3ec80e9647570e9a1229a9db65a18c082bfd346b282d8d62f2ed33f392c216953d723e3f65b21e36a169400ed2d0081cb79a2b05f17e5af52da5c94657d4ee091187652717a46b91ff2a00063fb585bacdf83166db8b3ed10b982a1185f8f4d319c58fb8b8f513490c4de0910889c28b747416fdd461bbc676880ed80e3536109925b2a76bf14b0496932ada65c9b5ac182f928e5fbd92b4a196d32df3d30c6c343e77ac81c0f03e3ac9e10bd6f9e16ecabb1c1d04340dac1ee41e2009c720a86417e9c92c39ded002de20bca144d20e9e5f4782"

df = pd.read_csv(url)

In [2]:
df.head

<bound method NDFrame.head of     Order_ID Customer_Name  Country       iPhone_Model Storage   Color  \
0       1001    Customer_1      USA          iPhone 13   256GB  Purple
1       1002    Customer_2   Canada          iPhone 12   256GB    Blue
2       1003    Customer_3   Canada  iPhone 15 Pro Max   512GB   Black
3       1004    Customer_4      USA  iPhone 15 Pro Max   512GB   Black
4       1005    Customer_5      USA          iPhone 15   128GB    Blue
..       ...           ...      ...                ...     ...     ...
95      1096   Customer_96      UAE      iPhone 14 Pro   256GB    Blue
96      1097   Customer_97       UK  iPhone 15 Pro Max   512GB   White
97      1098   Customer_98       UK  iPhone 15 Pro Max   512GB   White
98      1099   Customer_99  Germany  iPhone 15 Pro Max   512GB  Purple
99      1100  Customer_100       UK          iPhone 15   512GB    Blue

    Quantity  Price   Sale_Date Payment_Method
0          5   1817  2025-05-01     Debit Card
1          1    998  2025-03-05         PayPal
2          5    876  2025-01-25    Credit Card
3          2   1290  2025-03-24     Debit Card
4          3   1092  2025-02-01     Debit Card
..       ...    ...         ...            ...
95         1   1743  2025-03-09    Credit Card
96         3   1671  2025-02-08    Credit Card
97         4   1125  2025-01-08     Debit Card
98         5   1540  2025-02-04     Debit Card
99         3   1549  2025-03-28     Debit Card

[100 rows x 10 columns]>

In [3]:
df.columns

Index(['Order_ID', 'Customer_Name', 'Country', 'iPhone_Model', 'Storage',
       'Color', 'Quantity', 'Price', 'Sale_Date', 'Payment_Method'],
      dtype='object')

In [13]:
df.groupby("Country")["Price"].sum()

Country
Canada      26289
Germany     16515
Pakistan    12387
UAE         25085
UK          33148
USA         33451
Name: Price, dtype: int64

In [56]:
df.groupby("Country")["Quantity"].sum()

Country
Canada      55
Germany     35
Pakistan    35
UAE         52
UK          79
USA         77
Name: Quantity, dtype: int64

In [15]:
df.groupby("Storage")["Order_ID"].count()

Storage
128GB    34
256GB    38
512GB    28
Name: Order_ID, dtype: int64

In [20]:
df[(df["Color"]== "Black") & (df["Country"]=="USA")]

,Order_ID,Customer_Name,Country,iPhone_Model,Storage,Color,Quantity,Price,Sale_Date,Payment_Method
3,1004,Customer_4,USA,iPhone 15 Pro Max,512GB,Black,2,1290,2025-03-24,Debit Card
11,1012,Customer_12,USA,iPhone 14,128GB,Black,3,1572,2025-03-25,Cash
13,1014,Customer_14,USA,iPhone 12,512GB,Black,3,1743,2025-01-17,Credit Card
47,1048,Customer_48,USA,iPhone 14,256GB,Black,5,1786,2025-03-28,Cash
52,1053,Customer_53,USA,iPhone 14 Pro,128GB,Black,1,1959,2025-02-27,PayPal
55,1056,Customer_56,USA,iPhone 15,512GB,Black,5,1250,2025-01-02,Debit Card

In [21]:
df.Price.describe()

count     100.000000
mean     1468.750000
std       388.367637
min       718.000000
25%      1123.750000
50%      1571.500000
75%      1794.250000
max      1992.000000
Name: Price, dtype: float64

In [22]:
df["Country"].value_counts()

Country
USA         22
UK          22
Canada      18
UAE         17
Germany     11
Pakistan    10
Name: count, dtype: int64

In [34]:
import numpy as np

In [35]:
#700-1000 cheap 1000 - 1600 medium 1600> expensive

Conditions = [
    df["Price"]<=1000 ,
    (df["Price"]>1000) & (df["Price"]<=1600),
    df["Price"]>1600
]

values = ["Cheap","Medium","Expensive"]

In [37]:
df["Price_tag"] = np.select(Conditions,values, default="Unknown")

In [39]:
df.Price_tag.value_counts()

Price_tag
Expensive    47
Medium       38
Cheap        15
Name: count, dtype: int64

In [43]:
df.duplicated("Country", keep="first")

0     False
1     False
2      True
3      True
4      True
      ...
95     True
96     True
97     True
98     True
99     True
Length: 100, dtype: bool

### Dublicated ~ bu isaret dublicate olmayanlari gosterir

In [53]:
df[~df.duplicated("Country", keep="first")][["Country","Price"]]

    Country  Price
0       USA   1817
1    Canada    998
5       UAE   1939
6   Germany   1798
7        UK   1808
9  Pakistan   1670

In [47]:
df_last =df.duplicated("Country", keep="last")

In [50]:
df[~df_last][["Country","Price"]]

     Country  Price
80  Pakistan   1579
93       USA   1622
94    Canada   1388
95       UAE   1743
98   Germany   1540
99        UK   1549

In [55]:
df["iPhone_Model"].unique()

array(['iPhone 13', 'iPhone 12', 'iPhone 15 Pro Max', 'iPhone 15',
       'iPhone 14 Pro', 'iPhone 14'], dtype=object)

In [57]:
df["iPhone_Model"].nunique()

6

In [58]:
df.head()

,Order_ID,Customer_Name,Country,iPhone_Model,Storage,Color,Quantity,Price,Sale_Date,Payment_Method,Price_tag
0,1001,Customer_1,USA,iPhone 13,256GB,Purple,5,1817,2025-05-01,Debit Card,Expensive
1,1002,Customer_2,Canada,iPhone 12,256GB,Blue,1,998,2025-03-05,PayPal,Cheap
2,1003,Customer_3,Canada,iPhone 15 Pro Max,512GB,Black,5,876,2025-01-25,Credit Card,Cheap
3,1004,Customer_4,USA,iPhone 15 Pro Max,512GB,Black,2,1290,2025-03-24,Debit Card,Medium
4,1005,Customer_5,USA,iPhone 15,128GB,Blue,3,1092,2025-02-01,Debit Card,Medium

In [59]:
df.drop("Order_ID", axis=1)

,Customer_Name,Country,iPhone_Model,Storage,Color,Quantity,Price,Sale_Date,Payment_Method,Price_tag
0,Customer_1,USA,iPhone 13,256GB,Purple,5,1817,2025-05-01,Debit Card,Expensive
1,Customer_2,Canada,iPhone 12,256GB,Blue,1,998,2025-03-05,PayPal,Cheap
2,Customer_3,Canada,iPhone 15 Pro Max,512GB,Black,5,876,2025-01-25,Credit Card,Cheap
3,Customer_4,USA,iPhone 15 Pro Max,512GB,Black,2,1290,2025-03-24,Debit Card,Medium
4,Customer_5,USA,iPhone 15,128GB,Blue,3,1092,2025-02-01,Debit Card,Medium
...,...,...,...,...,...,...,...,...,...,...
95,Customer_96,UAE,iPhone 14 Pro,256GB,Blue,1,1743,2025-03-09,Credit Card,Expensive
96,Customer_97,UK,iPhone 15 Pro Max,512GB,White,3,1671,2025-02-08,Credit Card,Expensive
97,Customer_98,UK,iPhone 15 Pro Max,512GB,White,4,1125,2025-01-08,Debit Card,Medium
98,Customer_99,Germany,iPhone 15 Pro Max,512GB,Purple,5,1540,2025-02-04,Debit Card,Medium
99,Customer_100,UK,iPhone 15,512GB,Blue,3,1549,2025-03-28,Debit Card,Medium

In [67]:
df= df.set_index("Customer_Name")

KeyError: "None of ['Customer_Name'] are in the columns"

In [68]:
df.loc["Customer_1",:]

Order_ID                1001
Country                  USA
iPhone_Model       iPhone 13
Storage                256GB
Color                 Purple
Quantity                   5
Price                   1817
Sale_Date         2025-05-01
Payment_Method    Debit Card
Price_tag          Expensive
Name: Customer_1, dtype: object

In [75]:
df.loc[df["Color"]== "Purple",["Price","iPhone_Model"]]

               Price       iPhone_Model
Customer_Name
Customer_1      1817          iPhone 13
Customer_8      1808  iPhone 15 Pro Max
Customer_9      1381          iPhone 12
Customer_19     1010          iPhone 13
Customer_20     1588          iPhone 15
Customer_25     1571  iPhone 15 Pro Max
Customer_31     1135          iPhone 13
Customer_38     1674      iPhone 14 Pro
Customer_40     1034  iPhone 15 Pro Max
Customer_45     1667          iPhone 13
Customer_58     1752  iPhone 15 Pro Max
Customer_62     1769          iPhone 13
Customer_71     1977          iPhone 12
Customer_78     1464          iPhone 13
Customer_79     1790          iPhone 15
Customer_80     1819          iPhone 15
Customer_81     1579          iPhone 13
Customer_88      718  iPhone 15 Pro Max
Customer_99     1540  iPhone 15 Pro Max

In [76]:
df.drop("Customer_1")

,Order_ID,Country,iPhone_Model,Storage,Color,Quantity,Price,Sale_Date,Payment_Method,Price_tag
Customer_Name,,,,,,,,,,
Customer_2,1002,Canada,iPhone 12,256GB,Blue,1,998,2025-03-05,PayPal,Cheap
Customer_3,1003,Canada,iPhone 15 Pro Max,512GB,Black,5,876,2025-01-25,Credit Card,Cheap
Customer_4,1004,USA,iPhone 15 Pro Max,512GB,Black,2,1290,2025-03-24,Debit Card,Medium
Customer_5,1005,USA,iPhone 15,128GB,Blue,3,1092,2025-02-01,Debit Card,Medium
Customer_6,1006,UAE,iPhone 14 Pro,256GB,Red,5,1939,2025-02-15,Debit Card,Expensive
...,...,...,...,...,...,...,...,...,...,...
Customer_96,1096,UAE,iPhone 14 Pro,256GB,Blue,1,1743,2025-03-09,Credit Card,Expensive
Customer_97,1097,UK,iPhone 15 Pro Max,512GB,White,3,1671,2025-02-08,Credit Card,Expensive
Customer_98,1098,UK,iPhone 15 Pro Max,512GB,White,4,1125,2025-01-08,Debit Card,Medium
Customer_99,1099,Germany,iPhone 15 Pro Max,512GB,Purple,5,1540,2025-02-04,Debit Card,Medium
Customer_100,1100,UK,iPhone 15,512GB,Blue,3,1549,2025-03-28,Debit Card,Medium