# Panda

In [2]:
import pandas as pd 
import numpy as np

In [7]:
data = np.array([[1,4],[2,5],[3,6]])
df = pd.DataFrame(data,index =["row1","row2","row3"],
            columns=["col1","col2"])

In [8]:
df

      col1  col2
row1     1     4
row2     2     5
row3     3     6

In [16]:
data = [[1,4],[2,5],[3,6]]

In [17]:
df = pd.DataFrame(data,index =["row1","row2","row3"],
            columns=["col1","col2"])

In [18]:
df

      col1  col2
row1     1     4
row2     2     5
row3     3     6

In [22]:
iller = ['istanbul','adana','ankara','tekirdag']
plates = ["34","01","06","59"]

In [23]:
dict_iller = {"iller":iller, "plates": plates}

In [24]:
df_iller = pd.DataFrame(dict_iller)

In [33]:
df_iller.shape

(4, 2)

In [34]:
df_iller.info

<bound method DataFrame.info of       iller plates
0  istanbul     34
1     adana     01
2    ankara     06
3  tekirdag     59>

In [32]:
df_iller.iller

0    istanbul
1       adana
2      ankara
3    tekirdag
Name: iller, dtype: object

In [44]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
population = np.random.randint(0,10000000, size = 4)

In [41]:
df_iller['Population'] = population

In [42]:
df_iller

      iller plates  Population
0  istanbul     34     4725480
1     adana     01     3519273
2    ankara     06     2043968
3  tekirdag     59     4873037

In [45]:
cars = np.random.randint(0,10000000, size = 4)
house = np.random.randint(0,10000000, size = 4)

In [48]:
series1 = pd.Series(cars,index = np.arange(0,4))
series2 = pd.Series(house,index = np.arange(0,4))

In [49]:
df_iller = df_iller.assign(car_   number = series1, house_number = series2)

In [50]:
df_iller

      iller plates  Population  car_number  house_number
0  istanbul     34     4725480     9450218       1057615
1     adana     01     3519273     9379022       4174013
2    ankara     06     2043968     6609503       8200285
3  tekirdag     59     4873037     3209114       5395378